# Python Django
# Test a Django project with pytest on default az pipline agent

trigger:
- master

pool:
  name: Azure Pipelines
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 2.x'
  inputs:
    versionSpec: 2.x

- script: 'pip install -r Application/requirements.txt'
  displayName: 'Install dependencies'

- script: 'pip install pytest && pytest Tests/unit_tests --junitxml=../TestResults/test-results.xml && pip install pycmd && py.cleanup Tests/'
  displayName: pytest

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test-results.xml'
  inputs:
    testResultsFiles: '**/test-results.xml'
    searchFolder: '$(Common.TestResultsDirectory)'
    testRunTitle: 'Python Unit tests'

- task: ArchiveFiles@2
  displayName: 'Archive application'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Application'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'

- task: ArchiveFiles@2
  displayName: 'Archive Tests'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Tests'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/Tests$(Build.BuildId).zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
